from typing import Tuple

import numpy as np
from . import mixer

def array(sound: mixer.Sound) -> np.ArrayLike[np.uint8]: ...
def samples(sound: mixer.Sound) -> np.ArrayLike[np.uint8]: ...
def make_sound(array: np.ArrayLike[np.uint8]) -> mixer.Sound: ...
def use_arraytype(arraytype: str) -> mixer.Sound: ...
def get_arraytype() -> str: ...
def get_arraytypes() -> Tuple[str]: ...

