from typing import Tuple

import numpy as np
from . import surface

def array2d(surface: surface.Surface) -> np.ArrayLike[np.uint8]: ...
def pixels2d(surface: surface.Surface) -> np.ArrayLike[np.uint8]: ...
def array3d(surface: surface.Surface) -> np.ArrayLike[np.uint8]: ...
def pixels3d(surface: surface.Surface) -> np.ArrayLike[np.uint8]: ...
def array_alpha(surface: surface.Surface) -> np.ArrayLike[np.uint8]: ...
def pixels_alpha(surface: surface.Surface) -> np.ArrayLike[np.uint8]: ...
def pixels_red(surface: surface.Surface) -> np.ArrayLike[np.uint8]: ...
def pixels_green(surface: surface.Surface) -> np.ArrayLike[np.uint8]: ...
def pixels_blue(surface: surface.Surface) -> np.ArrayLike[np.uint8]: ...
def array_colorkey(surface: surface.Surface) -> np.ArrayLike[np.uint8]: ...
def make_surface(array: np.ArrayLike[np.uint8]) -> surface.Surface: ...
def blit_array(surface: surface.Surface, array: np.ArrayLike[np.uint8]) -> None: ...
def map_array(surface: surface.Surface, array3d: np.ArrayLike[np.uint8]) -> np.ArrayLike[np.uint8]: ...
def use_arraytype(arraytype: str) -> None: ...
def get_arraytype() -> str: ...
def get_arraytypes() -> Tuple[str]: ...
